python pic_deadline.py 1
python pic_deadline.py 2
python pic_deadline.py 3
python pic_deadline.py 4
python pic_deadline.py 5
python pic_deadline.py 6
python pic_deadline.py 7
python pic_deadline.py 8
python pic_deadline.py 9
python pic_deadline.py 10